// ─── Session ──────────────────────────────────────────────────────────────────

/** All inputs collected from the user at the start of a production session. */
export interface SessionContext {
  /** What the video is about — the only required field. */
  topic: string;
  /** Brand name, voice, and personality tone, e.g. "Nike — athletic, bold, aspirational". */
  brand?: string;
  /** Distribution platform: "Instagram" | "TikTok" | "YouTube Shorts" | "LinkedIn". */
  platform?: string;
  /** Intended outcome: "Awareness" | "Sales" | "Engagement" | "Education". */
  goal?: string;
  /** A creator, video, or visual aesthetic the user wants to reference or emulate. */
  reference?: string;
  /** Energy level that should permeate the video: "calm" | "hype" | "cinematic" | "raw" | "luxury". */
  mood?: string;
}

// ─── Script ───────────────────────────────────────────────────────────────────

/** A single timed beat in a video script, covering ~10 seconds of runtime. */
export interface ScriptBeat {
  /** Which narrative act this beat belongs to. */
  beat: "setup" | "tension" | "payoff";
  /** Timecode range, e.g. "0:00–0:10". */
  timecode: string;
  /**
   * Word-for-word voiceover text spoken during this beat.
   * Calibrated to ~130 wpm: 10s ≈ 22 words max.
   * Omit for silent / music-only beats.
   */
  voiceover?: string;
  /**
   * Text displayed on screen during this beat (caption or kinetic text).
   * Kept to ≤6 words for readability.
   */
  on_screen_text?: string;
  /** Visual direction note for the shot — what the camera is doing. */
  visual_direction: string;
}

/**
 * Full script for a single video concept.
 * Generated by the Claude API immediately after concepts are created.
 */
export interface VideoScript {
  /** References the parent IdeaConcept.id. */
  concept_id: string;
  /** The exact spoken or visual hook in the first 3 seconds. */
  hook_spoken: string;
  /** Three script beats covering the full narrative arc. */
  beats: ScriptBeat[];
  /**
   * Complete voiceover text concatenated across all beats.
   * Ready to paste into a TTS tool.
   */
  full_voiceover: string;
  /** Approximate word count of the full voiceover. */
  word_count: number;
  /** Estimated time to speak the full voiceover at 130 wpm, in seconds. */
  estimated_speaking_seconds: number;
}

// ─── Idea Generation ──────────────────────────────────────────────────────────

/**
 * Three-beat narrative spine for a short-form video.
 * Each beat maps to a ~10-second act within the total duration.
 */
export interface NarrativeArc {
  /** Act 1 (seconds 0–10): establishes subject, world, or question. */
  beat_1_setup: string;
  /** Act 2 (seconds 10–20): introduces conflict, contrast, or escalating tension. */
  beat_2_tension: string;
  /** Act 3 (seconds 20–30): delivers resolution, reveal, transformation, or CTA. */
  beat_3_payoff: string;
}

/** A single video concept generated by the idea agent. */
export interface IdeaConcept {
  /** Sequential identifier, e.g. "concept_01". */
  id: string;
  /** Five-word punchy title that captures the concept's angle. */
  title: string;
  /** First-three-second scroll-stopper: a visual action, spoken line, or pattern interrupt. */
  hook: string;
  /** Target distribution format. */
  format: "Reel" | "TikTok" | "YouTube Short" | "LinkedIn Video";
  /** Total runtime of the final video in seconds. */
  duration_seconds: number;
  /** Three-act narrative structure mapped to time. */
  narrative_arc: NarrativeArc;
  /**
   * Specific visual language descriptor combining lighting, palette, and camera feel.
   * Example: "golden hour cinematic with shallow depth of field" or "glitchy tech-noir".
   * Must be unique across all concepts in a generation batch.
   */
  visual_style: string;
  /**
   * Primary emotion the video is engineered to trigger in the viewer.
   * Must be unique across all concepts in a generation batch.
   */
  target_emotion: "FOMO" | "Awe" | "Humor" | "Inspiration" | "Curiosity" | "Desire";
  /** Number of main Higgsfield shots to generate (not counting b-roll). */
  shot_count: number;
  /** IDs of training CSV rows (e.g. "sheet1_12", "sheet2_04") that shaped this concept. */
  training_patterns_used: string[];
  /** Predicted scroll-stopping power on a 1–10 scale. */
  virality_score: number;
  /**
   * Concrete, specific explanation for the virality score.
   * Must not contain generic marketing language.
   * Must include "counterintuitive" or "challenges" for the contrarian concept.
   */
  virality_reasoning: string;
  /**
   * Full video script generated by a second Claude API call.
   * Present after `generateIdeas` resolves — undefined while generating.
   */
  script?: VideoScript;
}

// ─── Shot Prompts ─────────────────────────────────────────────────────────────

/**
 * A single Higgsfield video generation request.
 * The prompt must follow the 7-element formula:
 * SUBJECT + ACTION + ENVIRONMENT + LIGHTING + CAMERA MOVEMENT + MOOD + STYLE
 */
export interface ShotPrompt {
  /** Sequential identifier matching shot position, e.g. "shot_01". */
  shot_id: string;
  /** Which narrative beat this shot advances. B-roll shots provide visual texture. */
  narrative_beat: "setup" | "tension" | "payoff" | "broll";
  /** Requested clip length in seconds. Main shots: 3–5s. B-roll: 2–4s. */
  duration_seconds: number;
  /** Full 7-element Higgsfield prompt string. */
  prompt: string;
  /** Comma-separated list of elements to suppress in the generation. */
  negative_prompt: string;
  /** Output video aspect ratio. Always "9:16" for vertical social formats. */
  aspect_ratio: "9:16" | "1:1" | "16:9";
  /** Higgsfield generation style mode controlling the rendering pipeline. */
  style_preset: "photorealistic" | "cinematic" | "stylized";
  /** How pronounced camera movement and subject motion should be. */
  motion_intensity: "subtle" | "moderate" | "dynamic";
}

// ─── Remotion Scene Plan ──────────────────────────────────────────────────────

/** Animated text overlay configuration for a single scene. */
export interface CaptionConfig {
  /** The caption string to display. Keep under 8 words for readability. */
  text: string;
  /** Visual layout and animation style of the caption. */
  style: "bold_center" | "lower_third" | "kinetic" | "none";
  /** Frame number (at 30fps) when the caption fades / springs into view. */
  appear_at_frame: number;
  /** Frame number (at 30fps) when the caption fades out. */
  disappear_at_frame: number;
}

/** B-roll overlay effect applied on top of a scene clip. */
export interface BRollOverlay {
  /** Whether an overlay effect is active for this scene. */
  enabled: boolean;
  /** Which overlay effect to composite on top of the clip. */
  type: "none" | "zoom_punch" | "color_grade_shift" | "vignette_pulse";
}

/** A single timed clip in the Remotion timeline. */
export interface RemotionScene {
  /** Unique identifier for this scene, e.g. "scene_01". */
  scene_id: string;
  /** The frame at which this scene starts in the global timeline (0-indexed). */
  from_frame: number;
  /** How many frames this scene occupies. duration_frames * (1/fps) = seconds. */
  duration_frames: number;
  /**
   * References the ShotPrompt.shot_id whose generated clip this scene plays.
   * Used to inject the clip_url after Higgsfield generation completes.
   */
  clip_source: string;
  /** Resolved CDN URL of the Higgsfield clip. Injected by the assembly agent. */
  clip_url?: string;
  /** Transition style entering this scene from the previous one. */
  transition_in: "cut" | "fade" | "zoom_blur" | "glitch" | "whip_pan";
  /** Transition style leaving this scene into the next one. */
  transition_out: "cut" | "fade" | "zoom_blur" | "glitch" | "whip_pan";
  /** Animated text overlay for this scene. */
  caption: CaptionConfig;
  /** Optional visual effect composited over the clip. */
  broll_overlay: BRollOverlay;
  /** Guidance note for music / audio editing at this scene boundary. */
  audio_note: string;
}

/** Complete Remotion render configuration for the final video. */
export interface RemotionScenePlan {
  /** Must match the Remotion Composition id in Root.tsx, e.g. "FinalVideo". */
  composition_id: string;
  /** Frames per second for the render. Default: 30. */
  fps: number;
  /** Total frame count across all scenes combined. */
  total_duration_frames: number;
  /** Aspect ratio for the canvas. */
  aspect_ratio: "9:16" | "1:1" | "16:9";
  /** Ordered array of scenes. from_frame values must be contiguous and non-overlapping. */
  scenes: RemotionScene[];
  /** CSS-filter-based color grade applied globally across the entire video. */
  global_color_grade: "warm_cinematic" | "cold_tech" | "desaturated_raw" | "vibrant_pop";
  /** Font family name or style description for all caption overlays. */
  caption_font: string;
  /** Music energy and genre directive for the audio edit. */
  music_mood: "hype" | "cinematic" | "lo-fi" | "emotional" | "corporate";
}

// ─── Caption Copy ─────────────────────────────────────────────────────────────

/** Post caption copy ready to paste into the platform publisher. */
export interface CaptionCopy {
  /**
   * First visible line — must create a pattern interrupt or curiosity gap.
   * This is the only line visible before "more" is tapped on most platforms.
   */
  hook_line: string;
  /**
   * Supporting lines in order: expand the hook → create tension or revelation → deliver payoff or proof.
   * Typically 3–4 lines. Each should be a standalone sentence or fragment.
   */
  body_lines: string[];
  /** Platform-appropriate call to action. Should be low-friction and specific. */
  cta: string;
  /** Hashtag strings including the # prefix. Count follows platform_rules. */
  hashtags: string[];
  /** Tone and structural style of the copy. */
  caption_style: "punchy" | "storytelling" | "educational" | "contrarian";
}

// ─── Production Results ───────────────────────────────────────────────────────

/** Result returned by the Higgsfield client for one shot generation attempt. */
export interface GeneratedShot {
  /** Matches the ShotPrompt.shot_id that was submitted. */
  shot_id: string;
  /** CDN URL of the generated video clip. Empty string if status is not "success". */
  clip_url: string;
  /** CDN URL of the static thumbnail frame. Empty string if status is not "success". */
  thumbnail_url: string;
  /** Actual duration of the generated clip in seconds. */
  duration_seconds: number;
  /**
   * Generation result:
   * - "success"  — clip_url is valid and ready to use
   * - "failed"   — generation errored, error field contains the reason
   * - "skipped"  — failed after retry, pipeline continued without this shot
   */
  status: "success" | "failed" | "skipped";
  /** Human-readable error message. Present only when status is "failed" or "skipped". */
  error?: string;
}

/**
 * Complete deliverable package produced at the end of a session.
 * Contains every artifact needed for publishing or re-rendering.
 */
export interface ProductionPackage {
  /** The concept chosen by the user in step 2. */
  concept: IdeaConcept;
  /** All shot generation results, including any failures or skips. */
  shots: GeneratedShot[];
  /** Remotion scene plan with clip_urls injected from generated shots. */
  scene_plan: RemotionScenePlan;
  /** Caption copy for the post. */
  caption: CaptionCopy;
  /** Absolute local path to the rendered mp4, e.g. "./output/final_video_2026-05-06.mp4". */
  video_output_path: string;
}

// ─── Training Data Types ──────────────────────────────────────────────────────

/**
 * A named visual style with associated vocabulary banks.
 * Used by the prompt writer to select lighting, palette, and mood language
 * that matches the chosen concept's visual_style.
 */
export interface StyleGuide {
  /** Kebab-case identifier, e.g. "golden_hour_cinematic". */
  name: string;
  /** Lighting descriptors appropriate for this style, e.g. "warm natural sunlight". */
  lighting: string[];
  /** Hex values or named color descriptors for this style's palette. */
  color_palette: string[];
  /** Atmosphere and mood language phrases, e.g. "dreamy earthy vintage". */
  mood_descriptors: string[];
  /** Quality and rendering suffixes, e.g. "8K ultra-detailed", "film grain". */
  quality_markers: string[];
}

/**
 * A reusable structural template for the first 3 seconds of a video.
 * The idea agent samples these to ensure every hook is mechanically distinct.
 */
export interface HookPattern {
  /** Structural description of the hook pattern with [placeholder] slots. */
  pattern: string;
  /** The energy level this hook works best for. "any" means universally applicable. */
  energy: "calm" | "hype" | "cinematic" | "raw" | "luxury" | "any";
  /** A fully written example of this pattern in use. */
  example: string;
}

/**
 * Vocabulary banks the prompt writer pulls from when building Higgsfield shot prompts.
 * Injected verbatim into the system prompt so the model uses consistent terminology.
 */
export interface ShotVocabulary {
  /** Lighting setups and descriptions for shot prompts. */
  lighting: string[];
  /** Camera framing and movement descriptors. */
  camera_movements: string[];
  /** Atmosphere and vibe language. */
  mood_language: string[];
  /** Quality, rendering, and aesthetic suffixes appended to every shot prompt. */
  style_suffixes: string[];
}

/**
 * A reusable narrative structure template.
 * The idea agent maps concepts to these arcs before generating beat descriptions.
 */
export interface NarrativeArcTemplate {
  /** Short identifier, e.g. "reveal_arc" or "tension_release_arc". */
  name: string;
  /** What happens in act 1. */
  beat_1: string;
  /** What happens in act 2. */
  beat_2: string;
  /** What happens in act 3. */
  beat_3: string;
  /** Content types or goals this arc performs best for. */
  best_for: string[];
}

/**
 * Platform-specific publishing and copy rules.
 * The caption writer and idea agent use these to tailor output to the target platform.
 */
export interface PlatformRule {
  /** Platform name matching the SessionContext.platform value. */
  platform: string;
  /** Optimal video length for maximum completion rate on this platform. */
  optimal_duration_seconds: number;
  /** Recommended caption tone: "punchy" | "conversational" | "storytelling" | "educational". */
  caption_style: string;
  /** What kind of hook works best on this platform (audio-first, visual-first, etc.). */
  hook_style: string;
  /** Guideline for caption length, e.g. "under 150 characters". */
  caption_length: string;
  /** Recommended number of hashtags. */
  hashtag_count: number;
  /** Template or style for the call-to-action line. */
  cta_style: string;
}

/**
 * Root structure of training_prompts.json.
 * Loaded once at boot and referenced by all agents throughout the session.
 */
export interface TrainingPrompts {
  /** Semantic version of the training file, e.g. "1.0.0". */
  version: string;
  /** ISO date string of the last update, e.g. "2026-05-06". */
  last_updated: string;
  /** Named visual style guides with vocabulary banks. */
  style_guides: StyleGuide[];
  /** Structural hook templates for the first 3 seconds. */
  hook_patterns: HookPattern[];
  /** Vocabulary banks for building Higgsfield shot prompts. */
  shot_vocabulary: ShotVocabulary;
  /** Reusable three-act narrative structures. */
  narrative_arcs: NarrativeArcTemplate[];
  /** Per-platform publishing and copy rules. */
  platform_rules: PlatformRule[];
  /**
   * Phrases that are banned from all generated output.
   * The caption writer checks against this list and rewrites if any are found.
   */
  banned_phrases: string[];
}

// ─── CSV Training Data ────────────────────────────────────────────────────────

/** A single row parsed from the prompt training CSV files. */
export interface TrainingPromptRow {
  /** Unique row identifier, e.g. "sheet1_12" or "sheet2_04". */
  id: string;
  /** Which CSV file this row came from. */
  source_file: "prompts list - Sheet1.csv" | "prompts list - Sheet2.csv";
  /** The full prompt string (plain text or JSON serialised as a string). */
  prompt: string;
  /** Category label from the second column, e.g. "Image Generation / Fashion Photography". */
  metadata: string;
  /** Result of attempting to JSON.parse the prompt field. null if prompt is plain text. */
  parsed_prompt: Record<string, unknown> | null;
  /** High-level type derived from metadata, e.g. "Image Generation". */
  type: string;
  /** Specific subcategory derived from metadata, e.g. "Fashion Photography". */
  category: string;
}

/** Aggregated training data parsed from both CSV files. */
export interface TrainingData {
  /** Every row from both sheets combined. */
  examples: TrainingPromptRow[];
  /** Rows whose metadata includes "image generation". */
  image_generation_examples: TrainingPromptRow[];
  /** Rows whose metadata includes "fashion". */
  fashion_examples: TrainingPromptRow[];
  /** Rows whose metadata includes "cinematic". */
  cinematic_examples: TrainingPromptRow[];
}
